//! The pin, and the CSR, must be the ones the Python control plane expects.
//!
//! These are not unit tests of a helper. The pin is what stops a node from
//! accepting a trust bundle that did not come from its control plane, so a
//! Rust implementation that computes *a* pin rather than *the* pin does not
//! fail loudly — it silently accepts the wrong certificate authority. The
//! fixture here was generated by `spark_pulse.agent.identity.spki_pin`, and
//! `tests/test_agent_pin_interop.py` asserts the same fixture from the other
//! side, so neither implementation can drift without one of them going red.

use std::path::PathBuf;

fn fixture(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

fn expected_pin() -> String {
    let raw = fixture("pin.json");
    let value: serde_json::Value = serde_json::from_slice(&raw).expect("pin.json");
    value["pin"].as_str().expect("pin field").to_string()
}

#[test]
fn the_pin_matches_the_one_python_computes() {
    let pin =
        spark_pulse_agent::identity::spki_pin(&fixture("bundle.pem")).expect("computing the pin");
    assert_eq!(
        pin,
        expected_pin(),
        "the Rust pin disagrees with spark_pulse.agent.identity.spki_pin. A node \
         that computes a different pin will reject its own control plane's trust \
         bundle — or, worse, accept another one."
    );
}

#[test]
fn the_pin_does_not_depend_on_the_order_of_the_bundle() {
    // Both fixtures hold the same two CAs, concatenated the other way round.
    // The pin sorts the SPKIs precisely so that a control plane which writes
    // its bundle in a different order does not invalidate every enrolment.
    let forward = spark_pulse_agent::identity::spki_pin(&fixture("bundle.pem")).unwrap();
    let reversed = spark_pulse_agent::identity::spki_pin(&fixture("bundle-reversed.pem")).unwrap();
    assert_eq!(forward, reversed);
}

#[test]
fn an_empty_bundle_is_refused_rather_than_hashed_to_something() {
    // sha256 of nothing is a perfectly good hash, and a node that accepted it
    // would be pinned to "any bundle with no certificates in it".
    let err = spark_pulse_agent::identity::spki_pin(b"").unwrap_err();
    assert!(err.to_string().contains("no certificates"), "{err}");
}

#[test]
fn a_csr_is_p256_and_asks_for_no_identity() {
    // The control plane reads only the subject and the public key, and mints
    // the identity itself. A CSR that claimed a SAN would not be honoured, but
    // it would mean this agent was written as though it could choose.
    let pair = spark_pulse_agent::identity::build_csr(spark_pulse_agent::identity::CSR_COMMON_NAME)
        .expect("building a CSR");
    assert!(pair
        .csr_pem
        .starts_with("-----BEGIN CERTIFICATE REQUEST-----"));
    assert!(pair.key_pem.contains("PRIVATE KEY"));
    // Two calls, two keys. A node that reused a key across enrolments would
    // hand the control plane a public key it has already certified for a
    // different uuid.
    let other =
        spark_pulse_agent::identity::build_csr(spark_pulse_agent::identity::CSR_COMMON_NAME)
            .unwrap();
    assert_ne!(pair.key_pem, other.key_pem);
}
