# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spark_pulse.agent import agent_pb2 as spark__pulse_dot_agent_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spark_pulse/agent/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrollmentStub:
    """── Services ────────────────────────────────────────────────────────────────

    Bootstrap and certificate lifecycle.

    `Enroll` is reached over server-authenticated TLS with no client
    certificate, because the node does not have one yet; it is authenticated by
    a single-use enrollment token instead. `Renew` requires the mutually
    authenticated channel the agent already holds.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/sparkpulse.agent.v1.Enrollment/Enroll',
                request_serializer=spark__pulse_dot_agent_dot_agent__pb2.EnrollRequest.SerializeToString,
                response_deserializer=spark__pulse_dot_agent_dot_agent__pb2.Identity.FromString,
                _registered_method=True)
        self.Renew = channel.unary_unary(
                '/sparkpulse.agent.v1.Enrollment/Renew',
                request_serializer=spark__pulse_dot_agent_dot_agent__pb2.RenewRequest.SerializeToString,
                response_deserializer=spark__pulse_dot_agent_dot_agent__pb2.Identity.FromString,
                _registered_method=True)


class EnrollmentServicer:
    """── Services ────────────────────────────────────────────────────────────────

    Bootstrap and certificate lifecycle.

    `Enroll` is reached over server-authenticated TLS with no client
    certificate, because the node does not have one yet; it is authenticated by
    a single-use enrollment token instead. `Renew` requires the mutually
    authenticated channel the agent already holds.
    """

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Renew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=spark__pulse_dot_agent_dot_agent__pb2.EnrollRequest.FromString,
                    response_serializer=spark__pulse_dot_agent_dot_agent__pb2.Identity.SerializeToString,
            ),
            'Renew': grpc.unary_unary_rpc_method_handler(
                    servicer.Renew,
                    request_deserializer=spark__pulse_dot_agent_dot_agent__pb2.RenewRequest.FromString,
                    response_serializer=spark__pulse_dot_agent_dot_agent__pb2.Identity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sparkpulse.agent.v1.Enrollment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sparkpulse.agent.v1.Enrollment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Enrollment:
    """── Services ────────────────────────────────────────────────────────────────

    Bootstrap and certificate lifecycle.

    `Enroll` is reached over server-authenticated TLS with no client
    certificate, because the node does not have one yet; it is authenticated by
    a single-use enrollment token instead. `Renew` requires the mutually
    authenticated channel the agent already holds.
    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkpulse.agent.v1.Enrollment/Enroll',
            spark__pulse_dot_agent_dot_agent__pb2.EnrollRequest.SerializeToString,
            spark__pulse_dot_agent_dot_agent__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Renew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkpulse.agent.v1.Enrollment/Renew',
            spark__pulse_dot_agent_dot_agent__pb2.RenewRequest.SerializeToString,
            spark__pulse_dot_agent_dot_agent__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeSessionStub:
    """The command and liveness channel. mTLS only; the servicer rejects any
    stream whose peer did not present a certificate the CA signed.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/sparkpulse.agent.v1.NodeSession/Session',
                request_serializer=spark__pulse_dot_agent_dot_agent__pb2.AgentMessage.SerializeToString,
                response_deserializer=spark__pulse_dot_agent_dot_agent__pb2.ControlMessage.FromString,
                _registered_method=True)


class NodeSessionServicer:
    """The command and liveness channel. mTLS only; the servicer rejects any
    stream whose peer did not present a certificate the CA signed.
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=spark__pulse_dot_agent_dot_agent__pb2.AgentMessage.FromString,
                    response_serializer=spark__pulse_dot_agent_dot_agent__pb2.ControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sparkpulse.agent.v1.NodeSession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sparkpulse.agent.v1.NodeSession', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeSession:
    """The command and liveness channel. mTLS only; the servicer rejects any
    stream whose peer did not present a certificate the CA signed.
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sparkpulse.agent.v1.NodeSession/Session',
            spark__pulse_dot_agent_dot_agent__pb2.AgentMessage.SerializeToString,
            spark__pulse_dot_agent_dot_agent__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
