"""What gets copied to a node, and why it is a self-contained tarball.

**The decision.** One gzipped tar, built on the control plane, holding three
things: the ``spark_pulse`` package, every third-party module the agent
imports, and a launcher that puts them on ``sys.path`` in that order. It is
unpacked into ``<install root>/<version>-<digest>/`` and run by the node's own
``python3``. No pip, no venv, no wheel index, no network.

**Why not a wheel and a venv.** A venv is the obvious answer and it is the
wrong one here for one reason that outranks the rest: *an air-gapped fabric
link is normal on this hardware.* ``pip install`` — even ``--no-index
--find-links`` — still needs pip on the node, still needs a working
``ensurepip``, and still resolves and builds. Every one of those is a step that
can fail on a machine with no way to fetch a fix. Copying bytes and prepending
a path has no steps that can fail, and the failure it *can* have (a binary
built for the wrong interpreter) is detected at install time by
:data:`VERIFY_COMMAND` rather than at 3am by a unit that will not start.

**Where the third-party bytes come from.** The control plane's own environment.
It is a DGX Spark running DGX OS, and so is every node it enrolls: same
architecture, same CPython minor version, so ``grpcio``'s and ``cryptography``'s
extension modules load. That is an assumption, and assumptions on hardware get
checked rather than believed — which is what :data:`VERIFY_COMMAND` is: the
installer runs the launcher on the node immediately after unpacking, and a
mismatched extension module fails there, loudly, naming the module, with
nothing yet started.

**Upgrades and version skew.** The directory is named for the version and a
digest of its contents, and ``current`` is a symlink. Installing a newer agent
writes a new directory and flips the symlink, so the previous bytes are still
on disk and a rollback is one ``ln -sfn``. The identity directory is outside
the install root entirely, so neither an upgrade nor an uninstall touches it.
A node therefore keeps running its own version until it is upgraded — the
control plane moving ahead does not break it — and the version it is running
is visible in the hub, because the agent puts it in every ``Hello``.

**When the node already has the dependencies**, pass
``include_runtime=False``: the bundle is then a few hundred kilobytes of pure
Python and the node's own ``grpcio`` is used. The launcher prefers ``vendor/``
when it is present and falls through to the system path when it is not, so the
same launcher works for both.
"""

from __future__ import annotations

import hashlib
import io
import json
import logging
import tarfile
from dataclasses import dataclass
from importlib import util as import_util
from pathlib import Path

from spark_pulse.version import __version__

logger = logging.getLogger(__name__)

__all__ = [
    "AgentBundle",
    "DEFAULT_RUNTIME_MODULES",
    "LAUNCHER",
    "VERIFY_COMMAND",
    "build_bundle",
]

#: Top-level importable names the agent needs that are not ``spark_pulse``.
#:
#: Derived from what ``spark_pulse.agent.node_agent`` pulls in transitively:
#: gRPC and protobuf for the transport, ``cryptography`` (and the ``cffi``
#: machinery under it) for the CSR and the pin, the Docker SDK and its HTTP
#: stack for the executor, and PyYAML because ``spark_pulse.tools`` reads
#: recipes. A name that cannot be resolved on the control plane is skipped and
#: recorded, not fatal — the node may well have it already, and
#: :data:`VERIFY_COMMAND` is what decides.
DEFAULT_RUNTIME_MODULES: tuple[str, ...] = (
    "grpc",
    "google",
    "protobuf",
    "cryptography",
    "cffi",
    "_cffi_backend",
    "pycparser",
    "docker",
    "requests",
    "urllib3",
    "idna",
    "charset_normalizer",
    "certifi",
    "yaml",
    "_yaml",
)

#: Files and directories never shipped: build output, caches, and simulation
#: state. ``ui`` in particular is a compiled SPA of tens of megabytes that a
#: node has no use for.
_EXCLUDED = {"ui", "__pycache__", ".DS_Store", "data"}
_EXCLUDED_SUFFIXES = (".pyc", ".pyo", ".map")

#: The launcher. Deliberately tiny and dependency-free: it is the one piece
#: that must work before anything it sets up is importable.
LAUNCHER = """#!/usr/bin/env python3
# Generated by spark-pulse. Runs the node agent out of this bundle.
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
vendor = os.path.join(root, "vendor")
if os.path.isdir(vendor):
    # Ahead of the system path: the bundle's own grpcio is the one that was
    # tested against these stubs. Absent (include_runtime=False), the node's
    # installed packages are used instead and nothing here objects.
    sys.path.insert(0, vendor)
sys.path.insert(0, os.path.join(root, "lib"))

from spark_pulse.agent.__main__ import main

raise SystemExit(main())
"""

#: Run on the node the moment the bundle is unpacked. ``--help`` imports the
#: whole agent — gRPC, protobuf, cryptography, the Docker SDK — and exits 0, so
#: an extension module built for the wrong interpreter fails here, named, with
#: nothing installed and nothing started.
VERIFY_COMMAND = "--help"


@dataclass(frozen=True)
class AgentBundle:
    """The bytes to ship, and what they are."""

    version: str
    digest: str
    data: bytes
    includes_runtime: bool
    runtime_modules: tuple[str, ...] = ()
    missing_modules: tuple[str, ...] = ()

    @property
    def name(self) -> str:
        """The directory this unpacks into. Version *and* content, so two
        builds of one version never share a directory."""
        return f"{self.version}-{self.digest[:12]}"

    @property
    def size(self) -> int:
        return len(self.data)


def build_bundle(
    *,
    include_runtime: bool = True,
    runtime_modules: tuple[str, ...] | None = None,
    source_root: Path | None = None,
    cache_dir: Path | None = None,
) -> AgentBundle:
    """Build (or reuse) the bundle for this control plane's version.

    ``cache_dir`` makes a second install of the same version free: the bundle
    is content-addressed, so a cached file is either exactly the bytes that
    would be built or it is not used.
    """
    modules = (
        tuple(runtime_modules)
        if runtime_modules is not None
        else (DEFAULT_RUNTIME_MODULES if include_runtime else ())
    )
    package_root = source_root or Path(__file__).resolve().parent.parent

    resolved: list[tuple[str, Path, bool]] = []
    missing: list[str] = []
    for name in modules:
        location = _resolve_module(name)
        if location is None:
            missing.append(name)
            logger.debug("agent bundle: %s is not importable here; skipping", name)
            continue
        resolved.append((name, *location))

    buffer = io.BytesIO()
    # mtime is fixed and the member list is sorted, so the same inputs produce
    # the same bytes and therefore the same digest and the same directory name.
    with tarfile.open(fileobj=buffer, mode="w:gz", compresslevel=6) as tar:
        _add_tree(tar, package_root, "lib/spark_pulse")
        for name, path, is_dir in resolved:
            arcname = f"vendor/{path.name}"
            if is_dir:
                _add_tree(tar, path, arcname)
            else:
                _add_bytes(tar, arcname, path.read_bytes(), 0o644)
        _add_bytes(tar, "bin/spark-pulse-agent", LAUNCHER.encode(), 0o755)
        _add_bytes(
            tar,
            "BUNDLE.json",
            json.dumps(
                {
                    "version": __version__,
                    "includes_runtime": bool(resolved),
                    "runtime_modules": [name for name, _, _ in resolved],
                    "missing_modules": missing,
                },
                indent=2,
                sort_keys=True,
            ).encode(),
            0o644,
        )
    data = buffer.getvalue()
    bundle = AgentBundle(
        version=__version__,
        digest=hashlib.sha256(data).hexdigest(),
        data=data,
        includes_runtime=bool(resolved),
        runtime_modules=tuple(name for name, _, _ in resolved),
        missing_modules=tuple(missing),
    )
    if cache_dir is not None:
        cache_dir.mkdir(parents=True, exist_ok=True)
        (cache_dir / f"spark-pulse-agent-{bundle.name}.tar.gz").write_bytes(data)
    return bundle


def _resolve_module(name: str) -> tuple[Path, bool] | None:
    """Where ``name`` lives on this machine, and whether it is a package."""
    try:
        spec = import_util.find_spec(name)
    except (ImportError, ValueError):  # pragma: no cover - malformed install
        return None
    if spec is None:
        return None
    locations = list(spec.submodule_search_locations or [])
    if locations:
        return Path(locations[0]), True
    if spec.origin and spec.origin not in ("built-in", "frozen"):
        path = Path(spec.origin)
        if path.exists():
            return path, False
    return None


def _add_tree(tar: tarfile.TarFile, root: Path, arcname: str) -> None:
    """Add a directory, sorted, filtered, and with no local metadata."""
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in _EXCLUDED for part in relative.parts):
            continue
        if path.suffix in _EXCLUDED_SUFFIXES:
            continue
        if path.is_dir():
            continue
        if not path.is_file():  # sockets, dangling symlinks
            continue
        mode = 0o755 if path.stat().st_mode & 0o100 else 0o644
        _add_bytes(tar, f"{arcname}/{relative.as_posix()}", path.read_bytes(), mode)


def _add_bytes(tar: tarfile.TarFile, arcname: str, data: bytes, mode: int) -> None:
    info = tarfile.TarInfo(arcname)
    info.size = len(data)
    info.mode = mode
    info.mtime = 0
    info.uid = info.gid = 0
    info.uname = info.gname = "root"
    tar.addfile(info, io.BytesIO(data))


def unpack_for_test(bundle: AgentBundle, destination: Path) -> Path:
    """Unpack a bundle locally. Used by the simulated node, and by tests."""
    destination.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(bundle.data), mode="r:gz") as tar:
        _extract_all(tar, destination)
    return destination


def _extract_all(tar: tarfile.TarFile, destination: Path) -> None:
    for member in tar.getmembers():
        target = (destination / member.name).resolve()
        if not str(target).startswith(str(destination.resolve())):
            raise RuntimeError(f"refusing path traversal in bundle: {member.name}")
        target.parent.mkdir(parents=True, exist_ok=True)
        extracted = tar.extractfile(member)
        if extracted is None:
            continue
        target.write_bytes(extracted.read())
        target.chmod(member.mode)


def cached_bundle(cache_dir: Path, name: str) -> bytes | None:
    """Bytes of a previously built bundle, if the cache still holds them."""
    path = cache_dir / f"spark-pulse-agent-{name}.tar.gz"
    if path.exists():
        return path.read_bytes()
    return None


def prune_cache(cache_dir: Path, keep: int = 3) -> int:
    """Keep the newest ``keep`` bundles; return how many were removed."""
    if not cache_dir.is_dir():
        return 0
    files = sorted(
        cache_dir.glob("spark-pulse-agent-*.tar.gz"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    removed = 0
    for path in files[keep:]:
        path.unlink(missing_ok=True)
        removed += 1
    return removed
